version: '3.8'

services:
  backend:
    image: image001-backend
    container_name: backend
    ports:
      - "3001:3001"

  frontend:
    image: image001-frontend
    container_name: frontend
    ports:
      - "5173:5173"
